ARG BUILD_IMAGE=ghcr.io/graalvm/native-image:ol8-java11-22.2.0
ARG RUNTIME_IMAGE=oraclelinux:8-slim

# ---------------------------------------------------
# Resolve all maven dependencies
# ---------------------------------------------------
FROM ${BUILD_IMAGE} as dependencies
RUN microdnf -y install maven
WORKDIR /micronaut
COPY pom.xml ./
RUN mvn -B dependency:go-offline

# ---------------------------------------------------
# Build an artifact and create native image
# ---------------------------------------------------
FROM dependencies as build

COPY src ./src

RUN mvn -B clean package \
        -Dpackaging=native-image \
        -Dmaven.test.skip

# ---------------------------------------------------
# Build a container image containing native-image
# ---------------------------------------------------

FROM ${RUNTIME_IMAGE}
WORKDIR /app
COPY --from=build /micronaut/target/envchecker ./
COPY applicationinsights.json /opt/app/applicationinsights.json
COPY applicationinsights-agent-illuminate-3.3.1.jar /opt/app/applicationinsights-agent-illuminate-3.3.1.jar

ENTRYPOINT ["./envchecker"]

EXPOSE 8080
